# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# Enable future posts if desired:
# future: true

# Setup
title:               Jeffrey Wu
tagline:             "A Blog."
description:         "I write about random things, from programming stuff to photography and food."
url:                 https://jeffreywu1996.github.io
baseurl:             ""
plugins:             [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Jeffrey Wu
  url:               https://www.linkedin.com/in/jeffreywu1996
  email:             jeffreywu1996@gmail.com

# Custom vars
version:             1.0.0
github:              https://github.com/jeffreywu1996/
